from typing import Tuple
import numpy as np

class NvJpeg:
    def __init__(self) -> None: ...
    
    def decode(self, jpeg_data: bytes) -> np.ndarray: ...
    
    def encode(self, image: np.ndarray, quality: int = 70) -> bytes: ...
    
    def read(self, jpeg_file: str) -> np.ndarray: ...
    
    def write(self, jpeg_file: str, image: np.ndarray, quality: int = 70) -> None: ...
